In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [5]:
my_arr = np.arange(10)
print(my_arr)
print(type(my_arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [6]:
my_list = list(range(10))
print(my_list)
print(type(my_list))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [7]:
import numpy as np
import sys
S= range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
D= np.arange(1000)
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


In [8]:
print(type(S))

<class 'range'>


In [9]:
a=np.array(42)
print(a)

42


In [10]:
a=np.array([1,2,3,4,5,])
print(a)

[1 2 3 4 5]


In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print("Shape= ",data.shape)
print("Type= ",data.dtype)
print("Data = ", data)
print("\nAns1 = ",data * 10)
print("\nAns2= ",data+data)

Shape=  (2, 3)
Type=  float64
Data =  [[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

Ans1 =  [[ 15.  -1.  30.]
 [  0. -30.  65.]]

Ans2=  [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


In [16]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(type(arr))
print(arr)
print("\n", arr.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5]

 int64


In [17]:
zeros_arr = np.zeros((5,2))
eros_arr = np.zeros(5)
print(zeros_arr)
zeros_arr = np.zeros((2,3))
print(zeros_arr)
print("Data type of the array: ",zeros_arr.dtype)
zeros_arr_int = np.zeros((3,3), dtype=np.int16)
print("\nArray of zeros with integer elements: \n",zeros_arr_int)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
Data type of the array:  float64

Array of zeros with integer elements: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [18]:
ones_arr = np.ones(6)
print(ones_arr)
ones_arr = np.ones((3,2,4))
print("\n",ones_arr)
print("\n ndim= ",ones_arr.ndim)
print("\nData type of the array: ",ones_arr.dtype)
ones_arr_int = np.ones((2,2), dtype=np.int16)
print("\nArray of ones with integer elements: \n",ones_arr_int)

[1. 1. 1. 1. 1. 1.]

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

 ndim=  3

Data type of the array:  float64

Array of ones with integer elements: 
 [[1 1]
 [1 1]]


In [19]:
empty_arr = np.empty((3,2))
print(empty_arr)
print("\nData type of the array: ",empty_arr.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]

Data type of the array:  float64


In [20]:
identity_matrix = np.eye(3)
print(identity_matrix)
identity_matrix = np.eye(4)
print("\n",identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [22]:
arr = np.array([1, 2, 3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  [1 2 3] int64
After converting:  [1. 2. 3.] float32


In [23]:
arr = np.array([1.1, 2.2, 3.3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('i')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  [1.1 2.2 3.3] float64
After converting:  [1 2 3] int32


In [24]:
arr = np.array(['1.1', '2.2', '-3.3'])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  ['1.1' '2.2' '-3.3'] <U4
After converting:  [ 1.1  2.2 -3.3] float32


In [25]:
import numpy as np

arr = np.array(['1.1', '2.2', 'abc'])
print("Before converting: ", arr, arr.dtype)

try:
    new_arr = arr.astype(np.float64)
    print("After converting: ", new_arr, new_arr.dtype)
except ValueError as e:
    print("Conversion failed:", e)


Before converting:  ['1.1' '2.2' 'abc'] <U3
Conversion failed: could not convert string to float: np.str_('abc')


In [26]:
arr1 = np.arange(10)
arr2 = np.random.randn(10)
print("array 1\n",arr1, arr1.dtype)
print("Array 2 \n",arr2, arr2.dtype)
new_arr = arr1.astype(arr2.dtype)
print("New Array \n",new_arr, new_arr.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
Array 2 
 [ 1.49661793 -0.37582402 -0.50308854 -1.47073795 -0.74276211  0.13264157
 -0.99994277 -1.68244952 -0.06202618  0.01310742] float64
New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [27]:
str_arr = np.array(['hello', 'world', 'numpy'])
print(str_arr)

['hello' 'world' 'numpy']


In [28]:
import numpy as np
a = np.array([1., 2., 3., 4.])
b = np.array([5., 6., 7., 8.])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [29]:
a = np.array([1., 2., 3., 4.])
print(a + 1) # [2. 3. 4. 5.]
print(a - 1) # [0. 1. 2. 3.]
print(a * 2) # [2. 4. 6. 8.]
print(a / 2) # [0.5 1. 1.5 2. ]
print(a ** 2) # [ 1. 4. 9. 16.]
print(1/a)

[2. 3. 4. 5.]
[0. 1. 2. 3.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]
[ 1.  4.  9. 16.]
[1.         0.5        0.33333333 0.25      ]


In [30]:
arr = np.arange(12)
newarr = arr.reshape(4, 3)
print(newarr)
newarr = arr.reshape((4, 3),order='F')
print("\n",newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [31]:
arr = np.array([[1, 2, 3, 4,9,10], [5, 6, 7, 8,11,12]])
print(arr)
newarr = arr.reshape(3, 2, 2)
print("\n",newarr)
newarr1 = newarr.reshape(3, -1)
print("\n reshape(3,-1) \n",newarr1)

[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]

 reshape(3,-1) 
 [[ 1  2  3  4]
 [ 9 10  5  6]
 [ 7  8 11 12]]


In [32]:
original_array = np.array([[10, 20], [30, 40]])
print("Original array:\n", original_array)
flattened_array = original_array.flatten()
flattened_array[0] = 999
print("Flattened array:\n", flattened_array)
raveled_array = original_array.ravel()
raveled_array[1] = 888
print("Original array:\n", original_array)
print("Raveled array:\n", raveled_array)
print("Original array:\n", original_array)

Original array:
 [[10 20]
 [30 40]]
Flattened array:
 [999  20  30  40]
Original array:
 [[ 10 888]
 [ 30  40]]
Raveled array:
 [ 10 888  30  40]
Original array:
 [[ 10 888]
 [ 30  40]]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
r_arr = np.ravel(arr)
print("Flattened array:", r_arr)
r_arr[0] = 10
print("Original array after modification:", arr)
arr = np.array([[1, 2, 3], [4, 5, 6]])
f_arr = arr.flatten()
print("Flattened array:", f_arr)
f_arr[0] = 10
print("original array after flattening:", arr)

Flattened array: [1 2 3 4 5 6]
Original array after modification: [[10  2  3]
 [ 4  5  6]]
Flattened array: [1 2 3 4 5 6]
original array after flattening: [[1 2 3]
 [4 5 6]]


In [34]:
arr = np.array([1, 4, 9, 16])
result = arr ** 0.5
print(result) # Output: [1. 2. 3. 4.]

[1. 2. 3. 4.]


In [35]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 1], [3, 5]])
greater_than = arr1 > arr2
less_than = arr1 < arr2
equal_to = arr1 == arr2
print("Greater than:\n", greater_than)
print("\nLess than:\n", less_than)
print("\nEqual to:\n", equal_to)
arr3 = np.array([1, 2, 3])
arr4 = np.array([1, 2, 3])
arr5 = np.array([1, 2, 4])
result1 = np.array_equal(arr3, arr4) # True
result2 = np.array_equal(arr3, arr5) # False
print("\nArray-wise comparison 1:", result1)
print("Array-wise comparison 2:", result2)

Greater than:
 [[False  True]
 [False False]]

Less than:
 [[ True False]
 [False  True]]

Equal to:
 [[False False]
 [ True False]]

Array-wise comparison 1: True
Array-wise comparison 2: False


In [36]:
arr = np.arange(15)
arr.reshape((5, -1))
other_arr = np.ones((3, 5))
other_arr.shape
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
x = np.arange(10)
print("x= ",x)
print("\n x[:5]= ",x[:5])
print("\n x[5:]= ",x[5:])
print("\n x[4:7]= ",x[4:7])
print("\n x[::2]= ",x[::2])
print("\n x[1::2]= ",x[1::2])
print("\n x[::-1]= ",x[::-1])
print("\n x[5::-2]= ",x[5::-2])

x=  [0 1 2 3 4 5 6 7 8 9]

 x[:5]=  [0 1 2 3 4]

 x[5:]=  [5 6 7 8 9]

 x[4:7]=  [4 5 6]

 x[::2]=  [0 2 4 6 8]

 x[1::2]=  [1 3 5 7 9]

 x[::-1]=  [9 8 7 6 5 4 3 2 1 0]

 x[5::-2]=  [5 3 1]


In [38]:
x = np.arange(10)
print(x)
x[5:] = 2
print("\n After broadcasting1",x)
x[::2] = 100
print("\n After broadcasting2",x)

[0 1 2 3 4 5 6 7 8 9]

 After broadcasting1 [0 1 2 3 4 2 2 2 2 2]

 After broadcasting2 [100   1 100   3 100   2 100   2 100   2]


In [39]:
x = np.arange(10)
print("Original array:", x)
view = x[2:7]
print("View of the array:", view)
view[1:4] = 99
print("Modified view:", view)

Original array: [0 1 2 3 4 5 6 7 8 9]
View of the array: [2 3 4 5 6]
Modified view: [ 2 99 99 99  6]


In [40]:
X = np.arange(10)
print("Original array:", x)
view = x[2:7]
print("View of the array:", view)
view [1:4] = 99
print("Modified view:", view)

Original array: [ 0  1  2 99 99 99  6  7  8  9]
View of the array: [ 2 99 99 99  6]
Modified view: [ 2 99 99 99  6]


In [41]:
print("Original array after modifying the view:", x)
view [:]= -9
print("Modified view:", view)
print("Original array after modifying the view:", x)


Original array after modifying the view: [ 0  1  2 99 99 99  6  7  8  9]
Modified view: [-9 -9 -9 -9 -9]
Original array after modifying the view: [ 0  1 -9 -9 -9 -9 -9  7  8  9]


In [46]:
x2 = np.array([[12, 5, 2, 4],
[ 7, 6, 8, 8],
[ 1, 6, 7, 711]])
print(x2[0])
print(x2[1] [2])
print(x2[2, -1])
print(x2[0])

[12  5  2  4]
8
711
[12  5  2  4]


In [49]:
x3=np.array([[[12, 5, 2, 4],
[ 7, 6, 8, 8]],
[[ 1, 6, 7, 7],
[ 3, 4, 5, 9111]]])
print(x3[0])


[[12  5  2  4]
 [ 7  6  8  8]]


In [50]:
a = np.arange(12). reshape (3,4)
print("a= \n", a)
b = a > 4
print("b= \n",b)
print("a[b]= \n", a [b]) # 1d array
a [b] = 1
print("a= \n",a)


a= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= 
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]= 
 [ 5  6  7  8  9 10 11]
a= 
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [54]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28). reshape(7, 4)
print(names)
print("data= \n", data)
print("names bool= \n", names == 'Bob') # returns a boolean array
print("names == 'Bob' \n", data [names
== 'Bob'])


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
names bool= 
 [ True False False  True False False False]
names == 'Bob' 
 [[ 0  1  2  3]
 [12 13 14 15]]


In [56]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28). reshape(7, 4)
print(data [names != 'Bob'])
print("\n", data [~(names == 'Bob')])
data [names != 'Bob']=-1
print("\ndata= \n", data)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]

 [[ 4  5  6  7]
 [ 8  9 10 11]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]

data= 
 [[ 0  1  2  3]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [12 13 14 15]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
